### PR TITLE
Mocklibc subproject fixes

### PR DESCRIPTION
**Pull request by mbiebl**
Turn local modifications of mocklibc into patches and apply them via diff_files

The local copy of mocklibc was changed in
63ee649bd14c5dfa7985840061097bbac01ab721
5b8cd1a38696e7398e91863565dcfba792cbc744
0d78d1e4bf5ab3ce11678005b220aac0cfc5bee5

Turn those into patches and apply them via the diff_files mechanism.
This requires Meson 0.63.0, so bump the version accordingly.

https://mesonbuild.com/Wrap-dependency-system-manual.html#diff-files

Follow-up/Fix for #428

### CODE REVIEW

**Comment by mbiebl** [comment]
Will fix #182

**Comment by mbiebl** [comment]
@jrybar-rh this will raise the minimum required meson version to 0.63.0.
Unfortunately, Ubuntu Jammy i.e. 22.10, only has meson 0.61.2.
Should the CI be updated to use something newer, like 23.04 or 23.10?

**Comment by mbiebl** [comment]
Another alternative could be, to create a  PPA with a meson backport or use one of the existing ones at
https://launchpad.net/ubuntu/+ppas?name_filter=meson

**Comment by mbiebl** [comment]
https://launchpad.net/~spvkgn/+archive/ubuntu/build-tools

**Review by Brunojoes69 — APPROVED** [review]

**Pull request merged**
